ResearchCollectionsAndPreservation/scsb-circ

src/main/java/org/recap/ReCAPConstants.java, src/main/java/org/recap/controller/SharedCollectionRestController.java, src/main/java/org/recap/converter/MarcToBibEntityConverter.java, src/main/java/org/recap/model/BibliographicEntity.java, src/main/java/org/recap/model/ItemEntity.java, src/main/java/org/recap/model/report/SubmitCollectionReportInfo.java, src/main/java/org/recap/service/submitcollection/SubmitCollectionService.java
=> SubmitCollection changes

src/main/java/org/recap/service/submitcollection/SubmitCollectionService.java
=> Submit collection changes

src/main/resources/application-tst.properties, src/main/resources/application-uat.properties
updated the server port in tst and uat properties
=> updated the server port in tst and uat properties

src/main/java/org/recap/ReCAPConstants.java, src/main/java/org/recap/controller/SharedCollectionRestController.java, src/main/java/org/recap/converter/MarcToBibEntityConverter.java, src/main/java/org/recap/converter/SCSBToBibEntityConverter.java, src/main/java/org/recap/model/BibliographicEntity.java, src/main/java/org/recap/model/HoldingsEntity.java, src/main/java/org/recap/model/ItemEntity.java, src/main/java/org/recap/service/submitcollection/SubmitCollectionService.java, src/test/java/org/recap/submitcollection/SubmitCollectionServiceUT.java
Submit collection changes - to update owning institution bib,holding and item id
=> Submit collection changes - to update owning institution bib,holding and item id

src/main/java/org/recap/service/submitcollection/SubmitCollectionService.java
Updated null check condition in getBibEntityUsingBarcodeForIncompleteRecord method
=> Updated null check condition in getBibEntityUsingBarcodeForIncompleteRecord method

src/main/java/org/recap/service/submitcollection/SubmitCollectionService.java, src/test/java/org/recap/controller/SharedCollectionRestControllerUT.java, src/test/java/org/recap/submitcollection/SubmitCollectionServiceUT.java
RECAP-401 - Reject updation for existing bib having not existing barcode
=> RECAP-401 - Reject updation for existing bib having not existing barcode

src/main/java/org/recap/controller/SharedCollectionRestController.java, src/main/java/org/recap/converter/MarcToBibEntityConverter.java, src/main/java/org/recap/converter/SCSBToBibEntityConverter.java, src/main/java/org/recap/model/BibliographicEntity.java, src/main/java/org/recap/service/submitcollection/SubmitCollectionService.java
RECAP-415 - For incremental datadump
=> RECAP-415 - For incremental datadump

build.gradle
Added jacoco plugin for junit testcase
=> Added jacoco plugin for junit testcase

build.gradle, src/main/resources/application-junit.properties
updated junit property and sonar plugin
=> added junit property and sonar plugin

src/main/java/org/recap/controller/RequestItemController.java, src/main/java/org/recap/ils/JSIPConnectorFactory.java, src/main/java/org/recap/request/GFAService.java, src/main/java/org/recap/request/ItemEDDRequestService.java, src/main/java/org/recap/request/ItemRequestService.java, src/test/java/org/recap/controller/CancelItemControllerUT.java, src/test/java/org/recap/controller/RequestItemControllerUT.java, src/test/java/org/recap/controller/RequestItemValidatorControllerUT.java, src/test/java/org/recap/ils/NyplDataApiServiceUT.java, src/test/java/org/recap/model/ItemChangeLogEntityUT.java, src/test/java/org/recap/model/RequestStatusEntityUT.java, src/test/java/org/recap/processor/NyplJobResponsePollingProcessorUT.java, src/test/java/org/recap/request/GFAServiceUT.java, src/test/java/org/recap/request/ItemEDDRequestServiceUT.java, src/test/java/org/recap/request/ItemRequestDBServiceUT.java, src/test/java/org/recap/request/ItemValidatorServiceUT.java
Fixed junit test case issues in scsb-circ project
=> Fixed junit test case issues in scsb-circ project

src/main/java/org/recap/model/ItemRequestInformation.java
Recap-530 Modifies startPage field and endPage field Type to String
=> Recap-530 Modifies startPage field and endPage field Type to String

src/test/java/org/recap/request/RequestParamaterValidatorServiceUT.java
Recap-530 Updated UT for startPage field and endPage field Type to accept String
=> Recap-530 Updated UT for startPage field and endPage field Type to accept String

src/main/java/org/recap/request/ItemValidatorService.java
RECAP-596 : Fixed issue with placing request for multiple items.
=> RECAP-596 : Fixed issue with placing request for multiple items.

build.gradle, src/main/java/org/recap/ReCAPConstants.java, src/main/java/org/recap/camel/EmailPayLoad.java, src/main/java/org/recap/camel/EmailRouteBuilder.java, src/main/java/org/recap/camel/submitcollection/SubmitCollectionPollingFtpRouteBuilder.java, src/main/java/org/recap/camel/submitcollection/processor/SubmitCollectionNotificationProcessor.java, src/main/java/org/recap/camel/submitcollection/processor/SubmitCollectionProcessor.java, src/main/java/org/recap/controller/SharedCollectionRestController.java, src/main/java/org/recap/converter/MarcToBibEntityConverter.java, src/main/java/org/recap/converter/SCSBToBibEntityConverter.java, src/main/java/org/recap/model/ReportDataRequest.java, src/main/java/org/recap/model/csv/SubmitCollectionReportRecord.java, src/main/java/org/recap/service/submitcollection/SubmitCollectionReportGenerator.java, src/main/java/org/recap/service/submitcollection/SubmitCollectionService.java, src/main/resources/application-dev.properties, src/main/resources/application-junit.properties, src/main/resources/application-local-container.properties, src/main/resources/application-local.properties, src/main/resources/application-tst.properties, src/main/resources/application-uat.properties, src/main/resources/org/recap/camel/submit_collection_email_body.vm, src/test/java/org/recap/BaseTestCase.java, src/test/java/org/recap/service/submitcollection/SubmitCollectionReportGeneratorUT.java, src/test/java/org/recap/service/submitcollection/SubmitCollectionServiceUT.java
RECAP-587 - Added code changes for submit collection file process
=> RECAP-587 - Added code changes for submit collection file process

src/main/java/org/recap/service/submitcollection/SubmitCollectionService.java
Fixed exception report issue for submit collection
=> Fixed exception report issue for submit collection

src/main/java/org/recap/mqconsumer/RequestItemQueueConsumer.java
Recap 737 - Fixed long note Issues.
=> Recap 737 - Fixed long note Issues.

src/main/java/org/recap/camel/accessionreconcilation/AccessionReconcilationProcessor.java, src/main/java/org/recap/request/ItemRequestService.java, src/main/java/org/recap/request/ItemValidatorService.java, src/main/java/org/recap/request/RequestParamaterValidatorService.java, src/main/java/org/recap/service/deaccession/DeAccessionService.java, src/main/java/org/recap/service/submitcollection/SubmitCollectionReportGenerator.java, src/main/java/org/recap/service/submitcollection/SubmitCollectionService.java, src/main/resources/application-dev.properties, src/main/resources/application-junit.properties, src/main/resources/application-local-container.properties, src/main/resources/application-local.properties, src/main/resources/application-tst.properties, src/main/resources/application-uat.properties, src/main/resources/application.properties, src/test/java/org/recap/request/ItemValidatorServiceUT.java, src/test/java/org/recap/service/submitcollection/SubmitCollectionReportGeneratorUT.java, src/test/java/org/recap/service/submitcollection/SubmitCollectionServiceUT.java
RECAP-773 : Removed server.protocol property.
=> RECAP-773 : Removed server.protocol property.

src/main/java/org/recap/ReCAPConstants.java, src/main/java/org/recap/camel/statusreconciliation/StatusReconciliationController.java, src/main/java/org/recap/camel/submitcollection/processor/SubmitCollectionProcessor.java, src/main/java/org/recap/controller/SharedCollectionRestController.java, src/main/java/org/recap/service/submitcollection/SubmitCollectionDAOService.java, src/main/java/org/recap/service/submitcollection/SubmitCollectionService.java, src/main/resources/application.properties, src/test/java/org/recap/camel/statusreconciliation/StatusReconciliationControllerUT.java, src/test/java/org/recap/service/submitcollection/SubmitCollectionServiceUT.java
RECAP-819 : Removed the limit validation for FTP file processing and fixed the performance issue
=> RECAP-819 : Removed the limit validation for FTP file processing and fixed the performance issue

build.gradle, src/main/java/org/recap/camel/submitcollection/SubmitCollectionPollingFtpRouteBuilder.java
RECAP-828 : Provided the option to send the gzip file also to the submit collection ftp process.
=> RECAP-828 : Provided the option to send the gzip file also to the submit collection ftp process.

src/main/java/org/recap/ReCAPConstants.java, src/main/java/org/recap/camel/EmailRouteBuilder.java, src/main/java/org/recap/camel/submitcollection/SubmitCollectionPollingFtpRouteBuilder.java, src/main/java/org/recap/controller/SubmitCollectionJobController.java, src/main/resources/application.properties, src/main/resources/org/recap/camel/submit_collection_email_body_for_emptyDirectory.vm
Recap806-Batch Job for SubmitCollection
=> Recap806-Batch Job for SubmitCollection

src/main/java/org/recap/controller/SubmitCollectionJobController.java, src/main/resources/application.properties
Recap806-Removed values in  Application Properties for submit collection batch process
=> Recap806-Removed values in  Application Properties for submit collection batch process

src/main/java/org/recap/camel/submitcollection/SubmitCollectionPollingFtpRouteBuilder.java, src/main/java/org/recap/controller/SubmitCollectionJobController.java, src/main/resources/application-local.properties, src/main/resources/application.properties
Added conditions to check and start Route for Submit collection for each institutions
=> Added conditions to check and start Route for Submit collection for each institutions

src/main/java/org/recap/camel/submitcollection/SubmitCollectionPollingFtpRouteBuilder.java, src/main/java/org/recap/controller/SubmitCollectionJobController.java, src/main/resources/application-local.properties, src/main/resources/application.properties
Modified External Properties For SubmitCollection
=> Modified External Properties For SubmitCollection

src/main/java/org/recap/ReCAPConstants.java, src/main/java/org/recap/camel/submitcollection/SubmitCollectionPollingFtpRouteBuilder.java, src/main/java/org/recap/camel/submitcollection/processor/StartNextRoute.java, src/main/java/org/recap/controller/SubmitCollectionJobController.java, src/main/resources/application-local.properties
Submit collection job to run in sequence
=> Submit collection job to run in sequence

src/main/java/org/recap/ReCAPConstants.java, src/main/java/org/recap/converter/SCSBToBibEntityConverter.java
=> RECAP-864 - Fix for 1 bib multiple item submit collection issue

src/main/java/org/recap/ReCAPConstants.java, src/main/java/org/recap/camel/EmailRouteBuilder.java, src/main/java/org/recap/camel/requestinitialdataload/RequestDataLoadEmailService.java, src/main/java/org/recap/camel/requestinitialdataload/RequestInitialDataLoadPollingFtpRouteBuilder.java, src/main/resources/application.properties
Recap-866 Added Email for Request Initial Load Report and renamed the file names
=> Recap-866 Added Email for Request Initial Load Report and renamed the file names

src/main/java/org/recap/repository/ItemDetailsRepository.java, src/main/java/org/recap/service/submitcollection/SubmitCollectionDAOService.java, src/main/java/org/recap/service/submitcollection/SubmitCollectionReportHelperService.java
…barcode and owning institution item id are already link with another item
=> RECAP-829 - Fix for submit collection dummy record when the incoming barcode and owning institution item id are already link with another item

src/main/java/org/recap/ReCAPConstants.java, src/main/java/org/recap/camel/EmailPayLoad.java, src/main/java/org/recap/camel/EmailRouteBuilder.java, src/main/java/org/recap/camel/submitcollection/processor/SubmitCollectionProcessor.java, src/main/resources/application.properties, src/main/resources/org/recap/camel/submit_collection_email_body.vm
Recap-800 Changed filename and email content for submit collection
=> Recap-800 Changed filename and email content for submit collection

src/main/java/org/recap/camel/submitcollection/processor/StartNextRoute.java, src/main/java/org/recap/request/EmailService.java, src/main/resources/application.properties
Recap-800 Added CC's for request-recall and separate mailid for request-refile
=> Recap-800 Added CC's for request-recall and separate mailid for request-refile

src/main/resources/application.properties
Added external property in application.properties file ( request.recall.email.recap.cc =)
=> Added external property in application.properties file ( request.recall.email.recap.cc =)

src/main/java/org/recap/camel/dailyreconciliation/DailyReconciliationProcessor.java, src/test/java/org/recap/camel/DailyReconciliationProcessorUT.java
MS-40 Fixed Issue for too many cell exception in Daily-Reconciliation process
=> MS-40 Fixed Issue for too many cell exception in Daily-Reconciliation process

src/main/java/org/recap/ReCAPConstants.java, src/main/java/org/recap/camel/dailyreconciliation/DailyReconciliationRouteBuilder.java, src/main/java/org/recap/camel/submitcollection/SubmitCollectionPollingFtpRouteBuilder.java
Ms-50 Added code to process .gz files and process multiple files at the start of the job.
=> Ms-50 Added code to process .gz files and process multiple files at the start of the job

src/main/java/org/recap/service/submitcollection/SubmitCollectionReportHelperService.java, src/main/java/org/recap/service/submitcollection/SubmitCollectionValidationService.java
MS 213 Added error message for holding's id mismatch correponding to the item.
=> MS 213 Added error message for holding's id mismatch correponding to the item.

src/main/java/org/recap/ReCAPConstants.java, src/main/java/org/recap/camel/accessionreconciliation/AccessionReconciliationProcessor.java, src/main/java/org/recap/camel/accessionreconciliation/AccessionReconciliationRouteBuilder.java, src/main/java/org/recap/camel/accessionreconciliation/BarcodeReconcilitaionReport.java
MS-239 Adding customer code to Barcode reconciliation report
=> MS-239 Adding customer code to Barcode reconciliation report

src/main/java/org/recap/camel/accessionreconciliation/AccessionReconciliationProcessor.java
MS 239 Fixed issue to not display empty lines
=> MS 239 Fixed issue to not display empty lines

src/main/java/org/recap/camel/accessionreconciliation/AccessionReconciliationRouteBuilder.java
MS 239 Fixed issue which caused exception and terminated while processing the report
=> MS 239 Fixed issue which caused exception and terminated while processing the report

src/main/java/org/recap/ReCAPConstants.java, src/main/java/org/recap/repository/RequestItemDetailsRepository.java, src/main/java/org/recap/service/purge/PurgeService.java
Fix for Purge Email address according to Requirement.
=> Fix for Purge Email address according to Requirement.

src/main/java/org/recap/service/submitcollection/SubmitCollectionDAOService.java
MS-246 Fix for Submitcollection to process dummy records as boundwith with existing bibs
=> MS-246 Fix for Submitcollection to process dummy records as boundwith with existing bibs

src/main/java/org/recap/request/ItemRequestService.java
MS-252 Code change to checkin and checkout Columbia items
=> MS-252 Code change to checkin and checkout Columbia items

src/main/java/org/recap/controller/CancelItemController.java
MS-252 Code change to checkin and checkout Columbia items - Removed condition for Cancel Request
=> MS-252 Code change to checkin and checkout Columbia items - Removed condition for Cancel Request

src/main/java/org/recap/ils/NyplApiServiceConnector.java
Added log for NYPL job response
=> Added log for NYPL job response

src/main/java/org/recap/service/submitcollection/SubmitCollectionDAOService.java
MS-268 To update the isDeleted flag while performing submitcollection for bibs and holdings which are already Deaccessioned
=> MS-268 To update the isDeleted flag while performing submitcollection for bibs and holdings which are already Deaccessioned

src/main/java/org/recap/request/ItemRequestDBService.java, src/main/java/org/recap/request/ItemRequestService.java
MS-286,287,288 - Created a method in ItemRequestDBService to update a flag in requestItemEntity
=> MS-286,287,288 - Created a method in ItemRequestDBService to update a flag in requestItemEntity

src/main/java/org/recap/request/GFAService.java, src/main/java/org/recap/request/ItemRequestDBService.java, src/main/java/org/recap/request/ItemRequestService.java
MS-286,287,288 - Added logs and Pending Status to the list of requestStatusList
=> MS-286,287,288 - Added logs and Pending Status to the list of requestStatusList

src/main/java/org/recap/ReCAPConstants.java, src/main/java/org/recap/controller/RequestItemController.java
Ms-304 Removed a method which is unused and made correction in for a contanst field in RecapConstants.
=> Ms-304 Removed a method which is unused and made correction in for a contanst field in RecapConstants.

src/main/java/org/recap/request/ItemEDDRequestService.java
MS:323 send pseudopatron ID to LAS for EDD request.
=> MS:323 send pseudopatron ID to LAS for EDD request.

src/main/java/org/recap/request/ItemRequestService.java
Refile of first scan EDD request should also send pseudo patron barcode to LAS
=> Refile of first scan EDD request should also send pseudo patron barcode to LAS

src/main/java/org/recap/request/ItemEDDRequestService.java, src/main/java/org/recap/request/ItemRequestService.java
MS -328 Fixed issue on refile for first scan EDD request
=> MS -328 Fixed issue on refile for first scan EDD request

src/main/java/org/recap/request/GFAService.java, src/main/java/org/recap/request/ItemRequestService.java
Resubmit request by checking GFA status.
=> MS -322 Resubmit request by checking GFA status.

src/main/java/org/recap/ReCAPConstants.java, src/main/java/org/recap/controller/IdentifyPendingRequestsController.java, src/main/java/org/recap/repository/RequestItemDetailsRepository.java, src/main/java/org/recap/service/IdentifyPendingRequestService.java
To send email notification for pending and las item status request.
=> MS-338 To send email notification for pending and las item status request

src/main/java/org/recap/service/IdentifyPendingRequestService.java
MS-338 - Changes done for adding space between LAS and pending while sending email.
=> MS-338 - Changes done for adding space between LAS and pending while sending email.

src/main/java/org/recap/request/ItemRequestDBService.java
Bulk - Request : Sometimes the last barcode isn't processed properly.
=> MS -355 Bulk - Request : Sometimes the last barcode isn't processed properly.

src/main/java/org/recap/request/BulkItemRequestProcessService.java
MS -355 Bulk - Request : Sometimes the last barcode isn't processed properly. - changes
=> MS -355 Bulk - Request : Sometimes the last barcode isn't processed properly. - changes

src/main/java/org/recap/request/ItemRequestDBService.java
MS -355 Bulk - Request : Sometimes the last barcode isn't processed properly. - change
=> MS -355 Bulk - Request : Sometimes the last barcode isn't processed properly. - change

src/main/java/org/recap/request/BulkItemRequestProcessService.java
MS -355 Bulk - Request : Sometimes the last barcode isn't processed properly. - changes done
=> MS -355 Bulk - Request : Sometimes the last barcode isn't processed properly. - changes done

src/main/java/org/recap/request/ItemRequestDBService.java
MS-355 : Bulk - Request : Sometimes the last barcode isn't processed properly
=> MS-355 : Bulk - Request : Sometimes the last barcode isn't processed properly
